# Generated by Django 4.1.3 on 2022-12-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_type', models.CharField(choices=[('ISRC', 'ISRC'), ('ICPN', 'ICPN'), ('GRid', 'GRid'), ('ProprietaryID', 'ProprietaryID')], max_length=15)),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('pline_year', models.PositiveBigIntegerField()),
                ('pline_text', models.CharField(max_length=100)),
                ('cline_year', models.PositiveBigIntegerField()),
                ('cline_text', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Artist', 'Artist'), ('MainArtist', 'MainArtist'), ('other', 'Other')], max_length=50)),
                ('other_role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('ISRC', 'ISRC'), ('ICPN', 'ICPN'), ('GRid', 'GRid'), ('ProprietaryID', 'ProprietaryID')], max_length=15)),
                ('warning', models.CharField(max_length=20)),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('file', models.ImageField(upload_to='resources/')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('ISRC', 'ISRC'), ('ICPN', 'ICPN'), ('GRid', 'GRid'), ('ProprietaryID', 'ProprietaryID')], max_length=15)),
                ('identifier', models.CharField(max_length=20, unique=True)),
                ('pline_year', models.PositiveBigIntegerField()),
                ('pline_text', models.CharField(max_length=100)),
                ('cline_year', models.PositiveBigIntegerField()),
                ('cline_text', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('subgenre', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField()),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.album')),
                ('artists', models.ManyToManyField(to='models.artist')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.image')),
            ],
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('type', models.CharField(max_length=30)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.song')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='models.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.image'),
        ),
    ]
