# Generated by Django 4.1.3 on 2023-01-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, upload_to='resources/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('ISRC', 'ISRC'), ('ICPN', 'ICPN'), ('GRid', 'GRid'), ('ProprietaryId', 'ProprietaryId')], default='ProprietaryId', max_length=100)),
                ('id_value', models.CharField(default='I0', max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image_file', models.FileField(upload_to='resources/')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(default='Artist', max_length=250)),
                ('role', models.CharField(choices=[('MainArtist', 'MainArtist'), ('Singer', 'Singer'), ('Lyricist', 'Lyricist'), ('Composer', 'Composer'), ('Guitarist', 'Guitarist')], default='MainArtist', max_length=150)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('ISRC', 'ISRC'), ('ICPN', 'ICPN'), ('GRid', 'GRid'), ('ProprietaryId', 'ProprietaryId')], max_length=100)),
                ('id_value', models.CharField(default='S0', max_length=150, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('audio_file', models.FileField(upload_to='resources/')),
                ('has_crbt', models.BooleanField()),
                ('crbt_start_time', models.CharField(max_length=10)),
                ('crbt_code', models.CharField(max_length=50)),
                ('has_clip', models.BooleanField()),
                ('clip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.clip')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.image')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.party')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('ISRC', 'ISRC'), ('ICPN', 'ICPN'), ('GRid', 'GRid'), ('ProprietaryId', 'ProprietaryId')], default='ICPN', max_length=100)),
                ('id_value', models.CharField(default='A0', max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('song', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='models.song')),
            ],
        ),
    ]
