# Generated by Django 4.1.3 on 2023-01-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='release_type',
            field=models.CharField(choices=[('VideoSingle', 'VideoSingle'), ('ConcertVideo', 'ConcertVideo'), ('AudioDramaRelease', 'AudioDramaRelease'), ('Playlist', 'Playlist'), ('LongFormNonMusicalWorkVideoRelease', 'LongFormNonMusicalWorkVideoRelease'), ('ClassicalAlbum', 'ClassicalAlbum'), ('ShortFilm', 'ShortFilm'), ('VideoAlbum', 'VideoAlbum'), ('LyricSheetRelease', 'LyricSheetRelease'), ('MultimediaDigitalBoxedSet', 'MultimediaDigitalBoxedSet'), ('DramaticoMusicalVideoRelease', 'DramaticoMusicalVideoRelease'), ('VideoMastertoneRelease', 'VideoMastertoneRelease'), ('SheetMusicRelease', 'SheetMusicRelease'), ('Album', 'Album'), ('BookletRelease', 'BookletRelease'), ('Bundle', 'Bundle'), ('RingtoneRelease', 'RingtoneRelease'), ('MultimediaAlbum', 'MultimediaAlbum'), ('DigitalBoxSetRelease', 'DigitalBoxSetRelease'), ('ClassicalMultimediaAlbum', 'ClassicalMultimediaAlbum'), ('StemBundle', 'StemBundle'), ('AudioBookRelease', 'AudioBookRelease'), ('WallPaperRelease', 'WallPaperRelease'), ('BackCoverImageRelease', 'BackCoverImageRelease'), ('NonMusicalWorkBasedGameRelease', 'NonMusicalWorkBasedGameRelease'), ('MultimediaSingle', 'MultimediaSingle'), ('DjMix', 'DjMix'), ('EBookRelease', 'EBookRelease'), ('Season', 'Season'), ('RingbackToneRelease', 'RingbackToneRelease'), ('BookletBackImageRelease', 'BookletBackImageRelease'), ('SingleResourceRelease', 'SingleResourceRelease'), ('Single', 'Single'), ('ClassicalDigitalBoxedSet', 'ClassicalDigitalBoxedSet'), ('AsPerContract', 'AsPerContract'), ('Documentary', 'Documentary'), ('UserDefined', 'UserDefined'), ('MusicalWorkBasedGameRelease', 'MusicalWorkBasedGameRelease'), ('BookletFrontImageRelease', 'BookletFrontImageRelease'), ('AlertToneRelease', 'AlertToneRelease'), ('Drama', 'Drama'), ('Series', 'Series')], max_length=40),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('Artist', 'Artist'), ('Contributor', 'Contributor')], default='Artist', max_length=250),
        ),
        migrations.AlterField(
            model_name='party',
            name='role',
            field=models.CharField(choices=[('MainArtist', 'MainArtist'), ('Singer', 'Singer'), ('Lyricist', 'Lyricist'), ('Composer', 'Composer'), ('Guitarist', 'Guitarist')], default='MainArtist', max_length=150),
        ),
    ]
