# Generated by Django 4.1.3 on 2022-12-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='tests', max_length=100),
            preserve_default=False,
        ),
    ]
