# Generated by Django 4.1.3 on 2023-01-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_clip_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='party',
        ),
        migrations.AddField(
            model_name='song',
            name='party',
            field=models.ManyToManyField(to='models.party'),
        ),
    ]
