# Generated by Django 4.1.3 on 2023-01-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_order_release_type_alter_party_party_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='song',
        ),
        migrations.AddField(
            model_name='song',
            name='party',
            field=models.ManyToManyField(to='models.party'),
        ),
        migrations.AlterField(
            model_name='order',
            name='release_type',
            field=models.CharField(choices=[('Season', 'Season'), ('ClassicalMultimediaAlbum', 'ClassicalMultimediaAlbum'), ('MultimediaDigitalBoxedSet', 'MultimediaDigitalBoxedSet'), ('BookletBackImageRelease', 'BookletBackImageRelease'), ('Series', 'Series'), ('AsPerContract', 'AsPerContract'), ('Bundle', 'Bundle'), ('NonMusicalWorkBasedGameRelease', 'NonMusicalWorkBasedGameRelease'), ('VideoMastertoneRelease', 'VideoMastertoneRelease'), ('EBookRelease', 'EBookRelease'), ('Drama', 'Drama'), ('DigitalBoxSetRelease', 'DigitalBoxSetRelease'), ('ConcertVideo', 'ConcertVideo'), ('MultimediaSingle', 'MultimediaSingle'), ('ClassicalDigitalBoxedSet', 'ClassicalDigitalBoxedSet'), ('LongFormNonMusicalWorkVideoRelease', 'LongFormNonMusicalWorkVideoRelease'), ('AlertToneRelease', 'AlertToneRelease'), ('ShortFilm', 'ShortFilm'), ('BookletFrontImageRelease', 'BookletFrontImageRelease'), ('Single', 'Single'), ('StemBundle', 'StemBundle'), ('Playlist', 'Playlist'), ('BackCoverImageRelease', 'BackCoverImageRelease'), ('RingbackToneRelease', 'RingbackToneRelease'), ('AudioBookRelease', 'AudioBookRelease'), ('WallPaperRelease', 'WallPaperRelease'), ('RingtoneRelease', 'RingtoneRelease'), ('Album', 'Album'), ('DramaticoMusicalVideoRelease', 'DramaticoMusicalVideoRelease'), ('DjMix', 'DjMix'), ('LyricSheetRelease', 'LyricSheetRelease'), ('ClassicalAlbum', 'ClassicalAlbum'), ('AudioDramaRelease', 'AudioDramaRelease'), ('VideoAlbum', 'VideoAlbum'), ('SingleResourceRelease', 'SingleResourceRelease'), ('MultimediaAlbum', 'MultimediaAlbum'), ('Documentary', 'Documentary'), ('VideoSingle', 'VideoSingle'), ('BookletRelease', 'BookletRelease'), ('SheetMusicRelease', 'SheetMusicRelease'), ('UserDefined', 'UserDefined'), ('MusicalWorkBasedGameRelease', 'MusicalWorkBasedGameRelease')], max_length=40),
        ),
    ]
