# Generated by Django 4.1.3 on 2023-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_party_song_song_party_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='order',
            field=models.ManyToManyField(to='models.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='release_type',
            field=models.CharField(choices=[('UserDefined', 'UserDefined'), ('ShortFilm', 'ShortFilm'), ('BookletBackImageRelease', 'BookletBackImageRelease'), ('MultimediaAlbum', 'MultimediaAlbum'), ('MusicalWorkBasedGameRelease', 'MusicalWorkBasedGameRelease'), ('SheetMusicRelease', 'SheetMusicRelease'), ('ConcertVideo', 'ConcertVideo'), ('AsPerContract', 'AsPerContract'), ('StemBundle', 'StemBundle'), ('BookletRelease', 'BookletRelease'), ('VideoMastertoneRelease', 'VideoMastertoneRelease'), ('RingbackToneRelease', 'RingbackToneRelease'), ('AudioDramaRelease', 'AudioDramaRelease'), ('AlertToneRelease', 'AlertToneRelease'), ('DramaticoMusicalVideoRelease', 'DramaticoMusicalVideoRelease'), ('BackCoverImageRelease', 'BackCoverImageRelease'), ('ClassicalMultimediaAlbum', 'ClassicalMultimediaAlbum'), ('Single', 'Single'), ('EBookRelease', 'EBookRelease'), ('AudioBookRelease', 'AudioBookRelease'), ('BookletFrontImageRelease', 'BookletFrontImageRelease'), ('Documentary', 'Documentary'), ('DigitalBoxSetRelease', 'DigitalBoxSetRelease'), ('LyricSheetRelease', 'LyricSheetRelease'), ('VideoAlbum', 'VideoAlbum'), ('Drama', 'Drama'), ('NonMusicalWorkBasedGameRelease', 'NonMusicalWorkBasedGameRelease'), ('SingleResourceRelease', 'SingleResourceRelease'), ('MultimediaDigitalBoxedSet', 'MultimediaDigitalBoxedSet'), ('Playlist', 'Playlist'), ('VideoSingle', 'VideoSingle'), ('DjMix', 'DjMix'), ('RingtoneRelease', 'RingtoneRelease'), ('ClassicalDigitalBoxedSet', 'ClassicalDigitalBoxedSet'), ('Album', 'Album'), ('Season', 'Season'), ('WallPaperRelease', 'WallPaperRelease'), ('ClassicalAlbum', 'ClassicalAlbum'), ('Bundle', 'Bundle'), ('Series', 'Series'), ('MultimediaSingle', 'MultimediaSingle'), ('LongFormNonMusicalWorkVideoRelease', 'LongFormNonMusicalWorkVideoRelease')], max_length=40),
        ),
    ]
